flashbots/contender

- Cargo.lock
- Cargo.toml
- src/db/sqlite.rs
- src/generator/test_config.rs
- src/spammer/mod.rs
- univ2ConfigTest.toml
replaces the ad-hoc garbage parser with 
- ABI function parser from [alloy_json_abi](https://docs.rs/alloy-json-abi/0.8.0/alloy_json_abi/struct.Function.html)
- copy-paste function definitions from a smart contract into the config file to define our test calls
- unlocks ABI parsing for all types (though fuzzing is still not supported for dynamic or nested types)
- ABI calldata encoder from [foundry-common](https://foundry-rs.github.io/foundry/foundry_common/abi/index.html)
- very convenient, but could possibly be replaced with something simpler (is there something like this in alloy?)
> sane abi parsing

- src/bin/cli.rs
- src/generator/mod.rs
- src/generator/rand_seed.rs
- src/generator/seeder/mod.rs
- src/generator/seeder/rand_seed.rs
- src/generator/test_config.rs
- src/generator/univ2.rs
- src/spammer/mod.rs
- New traits `Seeder` and `SeedValue` allow devs to implement their own number-generators to use
- removed `Seeder` type bounds from `Spammer` and `Generator`
- Not all generators need seeders, so it's up to the writer of `impl Generator for YourStructHere` to manage their own `Seeder` (if they need one).
- `Spammer`'s implementation now only relies on an `impl Generator`.
A prime example of a `Generator` implementation is [here](https://github.com/zeroXbrock/contender/blob/general-fuzz-seeder/src/generator/test_config.rs#L79) -- this is used to generate txs from a [config file](https://github.com/zeroXbrock/contender/blob/general-fuzz-seeder/univ2ConfigTest.toml).
> general fuzz seeder

- Cargo.lock
- Cargo.toml
- src/bin/cli.rs
- src/generator/mod.rs
- src/generator/testfile.rs
- src/generator/util.rs
- src/spammer/blockwise.rs
- src/spammer/timed.rs
- src/spammer/util.rs
also removes the `foundry_common` dependency, removing the need for the `alloy-json-abi` dependency
> use Anvil in integration tests

- src/generator/testfile/mod.rs
- src/spammer/blockwise.rs
- src/spammer/mod.rs
- src/spammer/timed.rs
- src/spammer/util.rs
gives some flexibility to the callback by adding a hashmap along with the original named tx request to its params.
> change callback args; tx_req, hashmap

- src/spammer/blockwise.rs
- src/test_scenario.rs
additions to #24 
- **only query chain_id once at beginning of methods, and cleanup some errors**
> set-chain-id tweaks

- src/spammer/blockwise.rs
- src/spammer/tx_actor.rs
fixes two issues:
1. adding 1 to `last_block_number` (in blockwise spammer; used to lookup receipts by block number), which meant we never found any tx receipts, which would always fill up the cache.
a. at the end of the run, we'd find them by scanning over the whole range again, but for large runs this could waste a lot of time.
2. fetching receipts before the block was certain to have landed.
> fix spam cache bug

- src/spammer/blockwise.rs
no need to scan over previous blocks
> fix redundant scan in blockwise spammer

- README.md
- cli/src/commands.rs
- cli/src/main.rs
Adds checks at the start of setup & spam commands:
- sufficient balance (default 1 ETH; can be overridden by `--min-balance`)
- user passed all private keys used in the given config file
Also added all the default keys from anvil/hardhat, so the default examples will work with no private keys passed.
> prvkey ux improvements

- cli/src/main.rs
- src/generator/types.rs
- src/spammer/blockwise.rs
- src/spammer/mod.rs
- src/spammer/timed.rs
- src/spammer/tx_actor.rs
- src/test_scenario.rs
If a block on the target RPC contained a tx receipt with a non-standard type, or some other field that isn't present on base ethereum, deserialization would fail and crash the spammer.
To fix this, I generalized the expected response type (where relevant), by using `AnyNetwork` as our provider's network type (where relevant).
- new type alias `AnyProvider` replaces `RpcProvider` in several places (but not all)
- type that was `RpcProvider` renamed to `EthProvider`
`EthProvider` is used to do things we can't do with `AnyProvider`, like signing txs & estimating gas.
> support non-eth rpc providers

- crates/cli/src/main.rs
- crates/core/src/agent_controller.rs
- crates/core/src/generator/mod.rs
- crates/core/src/spammer/blockwise.rs
- scenarios/spamMe.toml
- fixed: same account was being used for every parallel tx sent by an agent (signer pool)
- fixed: same seed was being used for every agent
> differentiate seed using pool name, fix account index bug

- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/commands/mod.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/main.rs
- crates/cli/src/util.rs
- crates/core/src/generator/mod.rs
- crates/core/src/test_scenario.rs
- scenarios/univ2ConfigTest.toml
We required a hard-coded `from` address in setup steps, but this makes it potentially unsafe to test a scenario on a live chain. Placeholders are also easier to reason about.
Implement agent pools in the `setup` command so setup steps can use the `from_pool` setting.
> Advanced setup

- .gitignore
- crates/cli/src/commands/report.rs
- crates/cli/src/main.rs
- crates/core/src/spammer/tx_actor.rs
- **export report to report.csv by default**
- **fix ms-sec logging in report**
- save reports to `~/.contender/report.csv` by default
- keep DB in `~/.contender/contender.db`
should be able to run `contender report` with no args and get the latest report saved to `report.csv`
> save default file on report

- Cargo.lock
- Cargo.toml
- crates/cli/Cargo.toml
- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/main.rs
https://github.com/flashbots/contender/issues/77
- load/create `~/.contender/seed` at runtime in CLI
- use it as default, but still allow custom seed to be passed as before
> create, save, and load user seed: ~/.contender/seed

- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/commands/report.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/main.rs
https://github.com/flashbots/contender/issues/42
- add `-r` flag to `spam` command
- run `report` from `spam` if `-r` is passed, use filename given by `-r` to write report
> add -r flag to spam; runs report and saves to filename passed by -r

- README.md
- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/main.rs
- crates/cli/src/util.rs
- crates/core/src/spammer/blockwise.rs
- crates/core/src/spammer/util.rs
- crates/core/src/test_scenario.rs
Setting `--tps 10` should ideally generate 10 accounts in total, but scenarios with many agents were generating that many accounts *per agent*. This was sending ETH to lots of accounts that we'd never use, wasting lots of ETH.
When setting the number of accounts to generate for an agent, use `signers_per_period / from_pool_declarations.len()` (previously it was just `signers_per_period`).
If you have a number of agents not evenly divisible by the `txs_per_period`, then the number of accounts per agent will be rounded down. For example, if we set `--tps 10` and our scenario specifies 4 different `from_pool` declarations, we'll generate a total of 8 accounts. If we set `--tps 5` and still have 4 agents, we'll generate 4 accounts; 1 per agent.
This is fine because when selecting an agent …
> fix "too many accounts" bug

- crates/cli/src/util.rs
- crates/core/src/test_scenario.rs
- https://github.com/flashbots/contender/issues/89
- https://github.com/flashbots/contender/issues/87
Users were seeing low-level error messages during the funding step which didn't explain the high-level problem. This change stops you before that can happen.
- sum up total cost of funding accounts in `fund_accounts` and error if the sender has less than that balance
- takes into account gas price and adds 10% in case of future congestion
- shorten log to make it not seem like an error
> check funder balance is sufficient to fund all accounts before funding any

- crates/cli/src/commands/setup.rs
https://github.com/flashbots/contender/issues/86
- print more logs at end of setup
> add post-setup log

- crates/bundle_provider/src/bundle_provider.rs
- crates/cli/src/commands/spam.rs
- crates/core/src/agent_controller.rs
- crates/core/src/spammer/tx_actor.rs
- crates/core/src/test_scenario.rs
- scenarios/mempool.toml
https://github.com/flashbots/contender/issues/98
Added a new function `get_max_spam_cost`, which generates a sample selection of spam txs (fetching `gasLimit` and `gasPrice`) and returns the cost of the highest-costing transaction. Then we multiply that value by `duration` in the spammer to get the max ETH needed to fund a spammer agent.
Checking this value against `min_balance` in the spammer will ensure that the user provides enough ETH to each account to prevent any `insufficient funds` errors from cropping up mid-run.
> check spam cost before funding or spamming

- crates/core/src/generator/templater.rs
- crates/testfile/src/lib.rs
- crates/testfile/src/types.rs
Templating logic for finding placeholders fails with more than 2 placeholders in an arg, as the arg is not mutated, and the parsers starting point is not accumulating.
Accumulate last_end in the loop.
> fix: placeholder logic for > 2 placeholders

- crates/cli/src/commands/report/chart/heatmap.rs
- crates/cli/src/commands/report/template.html
default trace was breaking on chain that supports preState trace
delete default trace; it wasn't totally necessary anyways
also added page breaks to the html template for the html report generated by `contender report`
> report bugfix

- crates/cli/src/commands/spam.rs
- crates/core/src/generator/mod.rs
accounts not being funded before the scenario is initialized causes a crash because the TestScenario is trying to estimate gas usage with empty accounts.
- fund accounts before creating scenario
- error early with bad params
> spam bugfixes

- Cargo.lock
- crates/bundle_provider/Cargo.toml
- crates/bundle_provider/src/bundle_provider.rs
- crates/bundle_provider/src/lib.rs
- crates/core/Cargo.toml
- crates/core/src/test_scenario.rs
Most of the code in `bundle_provider` is in alloy and can be removed
Replace the duplicated `EthSendBundle` and bundle hash wrapper, also use alloy providers. Improves err handling style using `map_err`. Introduces a basic constructor for `EthSendBundle` that uses `..Default::default()` and does not require foreign impls on the alloy type
> chore(bundle_provider): rewrite BundleClient to use alloy

- crates/bundle_provider/src/bundle_provider.rs
The lack of parentheses or brackets seemed to affect the JSON here. This was erroring for me. Docs for reference:
https://docs.rs/alloy/0.3.6/alloy/providers/trait.Provider.html#method.raw_request
> bundle provider serialization fix

- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/commands/mod.rs
- crates/cli/src/commands/run.rs
- crates/cli/src/main.rs
Running the `run` command in CI.
Add flag `--sdp` to the `run` command, which skips the prompt.
When provided, contender will only deploy contracts if they have not been already.
> add flag to skip deploy prompt in 'run' command

- crates/core/src/spammer/spammer_trait.rs
- crates/core/src/spammer/tx_actor.rs
https://github.com/flashbots/contender/issues/127
Revamp how interrupts are handled in the spammer. Instead of using an atomic lock, we use `tokio::select!` to handle new signals while waiting for long-running functions to execute.
> fix ctrl-c handling

- Cargo.lock
- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/commands/run.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/default_scenarios/runconfig.rs
- crates/cli/src/main.rs
- crates/cli/src/util.rs
- crates/core/src/generator/mod.rs
- crates/core/src/generator/templater.rs
- crates/core/src/generator/types.rs
- crates/core/src/spammer/blockwise.rs
- crates/core/src/spammer/util.rs
- crates/core/src/test_scenario.rs
- crates/testfile/src/lib.rs
Hi, this is a great perf tool. I found that spammer sends EIP-1559 txs by default, which is fine, but sometimes eth-forked/custom node clients may not support EIP-1559 and therefore it is needed to be specified to send legacy txs.
So this PR adds the `legacy` option to specify sending legacy txs.
please review and feel free to comment.
> Set `TxType` for scenario txs

- .github/workflows/test.yml
This pull request includes changes to the GitHub Actions workflow to improve the build and test process. The most important changes include renaming the workflow file, updating the job names, and introducing a matrix strategy for different runner configurations.
Workflow file renaming and updates:
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L1-R1): Renamed from `.github/workflows/rust.yml` and updated the workflow name from "Build and Test" to "Test".
Matrix strategy introduction:
* [`.github/workflows/test.yml`](diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L14-R20): Updated the `build` job to use a matrix strategy with different runner configurations (`warp-ubuntu-latest-x64-32x` and …
> Add multi-arch support to test workflow

- .github/CODEOWNERS
This pull request includes a small change to the `.github/CODEOWNERS` file. The change assigns default ownership of the repository and the `.github` directory to specific team members.
Ownership assignments:
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R1-R5): Assigned `@zeroXbrock` as the default owner for everything in the repo, and both `@zeroXbrock` and `@sukoneck` as owners for the `.github` directory.
> Add codeowners for PR reviews

- crates/core/src/test_scenario.rs
lets users set `gas_limit` to allow [reverting] txs in setup
> accept pre-set gas_limit in setup steps

- Cargo.lock
- Cargo.toml
- crates/cli/src/commands/report/block_trace.rs
- crates/cli/src/commands/run.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/util.rs
- crates/core/src/spammer/tx_actor.rs
- crates/core/src/test_scenario.rs
upgrades alloy to 0.12.5 in anticipation of `engine_` api additions
> upgrade alloy

- crates/cli/src/commands/common.rs
- crates/cli/src/commands/run.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/main.rs
- crates/cli/src/util.rs
- crates/core/src/spammer/blockwise.rs
- crates/core/src/spammer/spammer_trait.rs
- crates/core/src/spammer/tx_actor.rs
- crates/core/src/spammer/tx_callback.rs
- crates/core/src/test_scenario.rs
- crates/testfile/src/lib.rs
If your spam txs get stuck in the tx pool (meaning they were received by the RPC as a valid tx but haven't been included onchain) then we would get stuck waiting for them, forcing us to shutdown our spam run or wait a long time.
Add a timeout that activates when the result collector hasn't seen any changes in the cache for some number of seconds. When the timeout is triggered, any txs that have been sitting in the cache for longer than the timeout will be removed. This allows `spamd` to start another run, generating new txs to replace the stalled ones.
The default timeout is `12` seconds. This can be changed by passing a CLI flag: `--timeout`, `--wait`, or `-w`
I also changed the default `duration` for spam commands to 1. If there are errors present, you should now see them sooner and not …
> drop stalled txs

- crates/cli/src/commands/mod.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/commands/spamd.rs
- crates/cli/src/main.rs
- crates/core/src/test_scenario.rs
Was seeing a lot of "replacement transaction underpriced" errors.
Started by adding a mechanism to automatically increase the gas price when we saw the error. The spammer increased the gas price a ton yet I still saw the error, which led me to find an inconspicuous bug in the priority fee calculation.
With that fixed, gas price increases happened much less frequently. I left the  `spamd` now reliably fills blocks on a live testnet until the accounts run out of gas, at which point contender must be manually stopped.
In `spamd`, automatically replenish funds in agent accounts
> gas price adder & priority fee bugfix

- crates/cli/src/commands/setup.rs
Fixes #149 
Adds a log in case contract deployment takes >10secs
Adds a log in case contract deployment takes >10secs
Should ideally use `info` or `warn` from `tracing` crate. Will add it if advised by maintainers
> feat: add timer warning on contract deployment

- crates/cli/src/default_scenarios/runconfig.rs
#182 
When getting this error (`intrinsic gas too low`), it means your tx doesn't use enough gas to be considered on this chain, so you need to use more gas.
When running `contender run fill-block` with a high number of transactions, the gas limit gets shrunk down because fill-block divides the block gas limit by the number of txs.
To compensate for this, we can (should have been able to) set `C_FILL_PERCENT` in the environment.
```sh
C_FILL_PERCENT=400 cargo run -- run fill-block -i 1 http://localhost:8545 -n 1000
```
But a (pointless) conditional was preventing percentages > 100 from being parsed, so I removed it.
> fix "intrinsic gas too low" error

- crates/cli/src/commands/spam.rs
invalid estimates; not erroring when it should, which causes errors later during runtime.
we forgot to multiply the per-tx max spam cost by the total number of transactions. fixed that.
> fix spam cost estimate bug

- Cargo.lock
- crates/cli/src/main.rs
- crates/core/Cargo.toml
- crates/core/src/provider.rs
If an RPC error occurs, we want to log it with max detail.
- debug! call in provider when it receives an error from `self.inner.call`
To see all debug logs, set `RUST_LOG=debug` in your environment:
```sh
RUST_LOG=debug cargo run -- spam ./scenarios/simple.toml --tps 100
```
Restricting `debug` logs to `contender_core` crate:
```sh
RUST_LOG=contender_core=debug cargo run -- spam ./scenarios/simple.toml --tps 100
```
> add debug log for failed provider calls

- README.md
- crates/cli/src/commands/common.rs
- crates/cli/src/commands/contender_subcommand.rs
- crates/cli/src/commands/spamd.rs
- crates/cli/src/main.rs
- crates/core/src/provider.rs
https://github.com/flashbots/contender/issues/210
Implemented as proposed in the issue.
`spam` just uses inner `spamd` function now, which made this a pretty easy job.
new flag is `--loops` (`-l`).
```sh
cargo run -- setup ./scenarios/simple.toml
cargo run -- spam ./scenarios/simple.toml --tps 100 -l
cargo run -- spam ./scenarios/simple.toml --tps 100 -l 10
cargo run -- spam ./scenarios/simple.toml --tps 100 -l 10 -d 20
```
> consolidate spamd

- .github/workflows/publish.yml
we really should just be using release-plz (but we gotta wait until we have everything ready for crates.io). ChatGPT really screwed up on this one.
> fix cargo-workspaces version in CI

- .github/workflows/test.yml
- crates/cli/src/commands/common.rs
- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/core/src/provider.rs
units were ambiguous; someone might enter a wei amount by accident, and it would be interpreted as an ether amount.
- parse with alloy's [`parse_units`](https://github.com/alloy-rs/core/blob/main/crates/primitives/src/utils/units.rs#L47)
- use `value_parser` macro (need to do this with more params; we have a lot of duplication because of not using this) 
examples:
```sh
cargo run -- setup --min-balance 1eth
cargo run -- setup --min-balance "0.15 ether"
cargo run -- setup --min-balance 500000gwei
```
Alloy's [Unit](https://github.com/alloy-rs/core/blob/main/crates/primitives/src/utils/units.rs#L440-L492) defines more denominations.
> take units with eth value in --min-balance

- Dockerfile
`setup` needs anvil.
installs in builder image and binary is copied into runtime image.
> add anvil bin to cli docker image

- crates/cli/src/commands/setup.rs
- crates/core/src/test_scenario.rs
recent changes broke setup: when deploying a contract that depends on a previous contract deployment, it would fail saying "address for named transaction not found in DB"
deployments must happen in the `load_txs` callback, otherwise the subsequent items will not have the contracts in the DB required to render the next step
> fix setup bug (must call contract deploy in load_txs callback)

- crates/cli/src/commands/setup.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/util/utils.rs
- crates/core/src/error.rs
- crates/core/src/generator/trait.rs
- crates/core/src/generator/types.rs
- crates/core/src/spammer/spammer_trait.rs
- crates/core/src/spammer/tx_callback.rs
- crates/core/src/spammer/util.rs
- crates/core/src/test_scenario.rs
- remove/replace over-engineered mpsc channels to pass errors from inside tokio tasks
- replace panics with errors
- return `Result<()>` from `OnTxSent` & `OnBatchSent` callbacks (`JoinHandle`s) for simpler error-handling within callbacks
the return type from `on_tx_sent` and `on_batch_sent` has changed from `Option<JoinHandle<()>>` to `Option<JoinHandle<crate::Result<()>>>`. This will require external callback implementations to modify their signatures, but will also allow them to use `?` syntax to handle errors!
> fix error-handling bugs

- crates/bundle_provider/src/bundle_provider.rs
- crates/core/src/generator/trait.rs
- crates/core/src/test_scenario.rs
If the chains addressed by `--rpc-url` and `--builder-url` have different chain_ids, you'll end up with an "invalid chain ID" error, which might make you think that there's a bug in contender. But what probably happened is that you provided an incorrect URL to one of the two.
> prevent chain_id mismatch btwn rpc & builder

- crates/report/src/block_trace.rs
- crates/report/src/chart/heatmap.rs
- crates/report/src/template.html.handlebars
- scenarios/bundles.toml
traces that weren't appropriate to decode were crashing reports.
print a warning instead of panicking when we fail to decode a trace frame
> fix error-handling in traces & heatmap

- .gitignore
This isn't in the gitignore and some PRs contain an added .DS_Store
add .DS_Store to gitignore
> chore(gitignore): ignore .DS_Store

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- crates/cli/Cargo.toml
- crates/cli/src/commands/common.rs
- crates/cli/src/commands/spam.rs
- crates/cli/src/commands/spamd.rs
- crates/cli/src/main.rs
- crates/cli/src/util/provider.rs
- crates/cli/src/util/utils.rs
- crates/core/src/spammer/spammer_trait.rs
- crates/engine_provider/src/auth_provider.rs
- crates/engine_provider/src/engine.rs
- crates/engine_provider/src/lib.rs
- crates/engine_provider/src/valid_payload.rs
fixes https://github.com/flashbots/contender/issues/277
It's not straightforward or necessarily reliable to determine a target chain's hard-fork status at runtime, so instead of trying to detect it automatically, I just added new CLI flag `-m` to specify which message version to use (`v1` through `v4`).
Tested v4 execution payloads successfully using reth as described [in the issue](https://github.com/flashbots/contender/issues/277).
> support V4 (Prague) execution payloads

- crates/core/src/test_scenario.rs
- crates/core/src/util.rs
on chains that don't support blobs, calling `eth_getBlobBaseFee` produces an error, which in most cases, crashes contender.
use a new helper function `get_blob_fee_maybe` which behaves as follows: if the call to `eth_getBlobBaseFee` fails, log a warning and return 0.
Some chains don't support blobs and that's OK <3
> ignore blob fee error; if call fails, return 0

- crates/core/src/test_scenario.rs
```
Error: failed to prepare tx failed to estimate gas for tx 
ErrorResp(ErrorPayload { code: -32003, message: "max fee per blob gas less than block blob gas fee", data: None }
```
add `max_fee_per_blob_gas` and `blob_versioned_hashes` to the tx request before estimating gas.
> add blob params to blob tx reqs when estimating gas
