flashbots/contender

scenarios/univ2ConfigTest.toml

uniV2 config broken
new spam directives

update uniV2 scenario to new spec

---

README.md

- command missing
- intro to scenarios missing
- want some common examples to get people acquainted with running the CLI

README: add example calls & explainers for highly-recommended options

---

crates/cli/src/commands/setup.rs
crates/core/src/test_scenario.rs

- https://github.com/flashbots/contender/issues/74
- https://github.com/flashbots/contender/issues/64
Catch common errors where they occur, add some custom logic to parse them and print helpful messages on occurrence.

improve logs from common errors in spam & setup

---

crates/cli/src/commands/setup.rs
crates/cli/src/util.rs

https://github.com/flashbots/contender/issues/85
- `panic!` should not have been used. It's been replaced with a proper `Error`.
- added more details to funding-related error messages
~~- [ ] Added Tests~~
~~- [ ] Added Documentation~~
~~- [ ] Breaking changes~~

improve funding errors

---

README.md
docs/creating_scenarios.md

Need to start writing docs. Lots of high-level ideas are solidifying in this project (I keep using them), so I need to start documenting it so that others can understand wtf I'm talking about.
I've started with a guide to writing new scenario files, which explains all the features of scenario files while providing simple examples and skeleton code.

add 'new scenario' guide & docs directory

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/report/chart/heatmap.rs
crates/cli/src/commands/report/gen_html.rs
crates/cli/src/commands/report/mod.rs
crates/cli/src/commands/report/template.html
crates/cli/src/commands/run.rs
crates/cli/src/commands/spam.rs
crates/cli/src/default_scenarios/runconfig.rs
crates/cli/src/main.rs
crates/core/src/db/mock.rs
crates/core/src/db/mod.rs
crates/sqlite_db/src/lib.rs

some minor fixes to reports. adds run metadata, and saves scenario_name in `runs` table

report touchups

---

crates/core/src/spammer/spammer_trait.rs

Saw this was using a mutex when using an `Arc<AtomicBool>` is a pretty common way to do cancellation
Use an `Arc<AtomicBool>` instead of `Mutex<bool>`

chore(spammer): use AtomicBool for cancel signal

---

crates/cli/src/commands/report/template.html

Change graph background color to white

Change background color

---

README.md

- **update readme w/ new badges**

multi arch testing badges

---

crates/cli/src/commands/report/block_trace.rs
crates/cli/src/commands/report/cache.rs
crates/cli/src/commands/report/chart/gas_per_block.rs
crates/cli/src/commands/report/mod.rs

`report` was failing when calling unichain.
Switched relevant types to `AnyRpcBlock` and `AnyNetwork`

bugfix: switch block type in report to Any

---

crates/cli/src/commands/setup.rs
crates/cli/src/commands/spam.rs
crates/cli/src/util.rs
crates/core/src/agent_controller.rs
crates/core/src/spammer/blockwise.rs
crates/core/src/spammer/util.rs
crates/core/src/test_scenario.rs
crates/testfile/src/types.rs

Using contender as a library proved cumbersome.
Moves some util functions into relevant struct impls to make them more easily accessible.

core api improvements

---

README.md

following #154, forgot to update readme

testconfig api readme

---

Cargo.lock
crates/cli/src/commands/run.rs
crates/core/Cargo.toml
crates/core/src/lib.rs
crates/core/src/provider.rs
crates/core/src/test_scenario.rs

https://github.com/flashbots/contender/issues/153
custom layer implementation to inject into test_scenario provider

log request id w/ hash when calling sendRawTransaction

---

crates/cli/src/commands/contender_subcommand.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/spam.rs
crates/cli/src/default_scenarios/runconfig.rs
crates/core/src/db/mock.rs
crates/core/src/db/mod.rs
crates/core/src/generator/trait.rs
crates/core/src/generator/types.rs
crates/core/src/spammer/blockwise.rs
crates/core/src/spammer/spammer_trait.rs
crates/core/src/test_scenario.rs
crates/sqlite_db/src/lib.rs

- **cleanup flush_tx_cache**
- **make fill-block get closer to block limit**
- **change default interval & num_txs for fill-block, change some usizes to u64s**
- sub-second intervals for fill-block
- usizes where u64 is better
make the ugly things prettier

quality-of-life fixes

---

.github/workflows/preview-report.yml
README.md
crates/cli/src/commands/common.rs
crates/cli/src/commands/contender_subcommand.rs
crates/cli/src/commands/spam.rs

PR for the issue https://github.com/flashbots/contender/issues/195
Converted `rpc-url` into an option from an argument, with default value as `http://localhost:8545`

Added default RPC value as http://localhost:8545

---

.github/workflows/publish.yml

fix invalid rust toolchain action

release CI

---

crates/cli/src/commands/mod.rs

see contender version you're running
clap derive macro

add -V to contender cli

---

Cargo.lock
crates/bundle_provider/CHANGELOG.md
crates/bundle_provider/Cargo.toml
crates/cli/CHANGELOG.md
crates/cli/Cargo.toml
crates/core/CHANGELOG.md
crates/core/Cargo.toml
crates/engine_provider/CHANGELOG.md
crates/engine_provider/Cargo.toml
crates/sqlite_db/CHANGELOG.md
crates/sqlite_db/Cargo.toml
crates/testfile/CHANGELOG.md
crates/testfile/Cargo.toml

chore: bump version

---

crates/cli/src/commands/admin.rs

Fixes #278 
Log the generated private keys on running `admin accounts`

feat: show private keys on admin account

---

crates/report/src/block_trace.rs
crates/report/src/command.rs

Reverting txs don't land, so if you're testing those, you'd have no txs in your report, which would cause an error and prevent your making a report.
If no txs are found onchain, estimate the block range using data from the `runs` table.

estimate block range in report if no txs land

---

crates/cli/src/util/utils.rs

default to 0 if blob fee method not allowed

---

Cargo.lock
crates/bundle_provider/CHANGELOG.md
crates/bundle_provider/Cargo.toml
crates/cli/CHANGELOG.md
crates/cli/Cargo.toml
crates/core/CHANGELOG.md
crates/core/Cargo.toml
crates/engine_provider/CHANGELOG.md
crates/engine_provider/Cargo.toml
crates/report/CHANGELOG.md
crates/report/Cargo.toml
crates/sqlite_db/CHANGELOG.md
crates/sqlite_db/Cargo.toml
crates/testfile/CHANGELOG.md
crates/testfile/Cargo.toml
scripts/release-version.sh

- blob support
- eip7702 (setCode) support
- new builtin scenarios:
- blobs
- erc20
- reverts
- custom contract
- setCode
- improved error messages

version 0.4.0

---

README.md
docs/architecture.md
docs/cli.md
docs/engine-api.md
docs/examples.md
docs/installation.md
docs/library-usage.md
docs/overview.md
docs/placeholders.md
docs/reports-db-admin.md
docs/scenarios.md

simplifies the root README to core basics & table of contents linking to docs/
some new content added for new features as well

simplify readme, move meat to docs/

---

crates/cli/src/commands/spam.rs

fixes https://github.com/flashbots/contender/issues/313
use legacy txs for funding

use legacy tx type for funding txs

---

crates/cli/src/default_scenarios/setcode/base.rs
crates/core/src/test_scenario.rs
scripts/2_tag-version.sh

fixes https://github.com/flashbots/contender/issues/331
fork the target RPC in anvil

fork target RPC URL with anvil on estimate_setup_cost

---

Cargo.lock
crates/core/src/db/mock.rs
crates/core/src/db/mod.rs
crates/core/src/generator/templater.rs
crates/core/src/generator/trait.rs
crates/core/src/test_scenario.rs
crates/sqlite_db/Cargo.toml
crates/sqlite_db/src/lib.rs
crates/testfile/src/lib.rs

resolves https://github.com/flashbots/contender/issues/190

add genesis_hash to RPC URL identity
